version: 0.2.0.{build}
os: Visual Studio 2015
configuration: Release
platform: Any CPU
environment:
  COVERALLS_REPO_TOKEN:
    secure: bFVGoXLR4/8VSClNH2s5qhXfJNwbJPbggNv6grvl+JaITuMkHLqvCw+48T0uKyFI
before_build: 
- cmd: >-
    cd GoogleTestExtension

    SetVersion $env:APPVEYOR_BUILD_VERSION
build:
  project: GoogleTestExtension\GoogleTestExtension.sln
  verbosity: normal
test_script:
- ps: >-
    $opencover = (Resolve-Path "GoogleTestExtension/packages/OpenCover.*/tools/OpenCover.Console.exe").ToString()

    $coveralls = (Resolve-Path "GoogleTestExtension/packages/coveralls.net.*/tools/csmacnz.coveralls.exe").ToString()

    & $opencover -register:user -target:VsTest.Console.exe "-targetargs:/logger:Appveyor GoogleTestExtension\GoogleTestAdapterTests\bin\$env:CONFIGURATION\GoogleTestAdapterTests.dll" "-filter:+[*]* -[GoogleTestAdapterTests]*" -output:OpenCover_CoverageData.xml -returntargetcode

    $TestExitCode = $LASTEXITCODE

    & $coveralls --opencover -i OpenCover_CoverageData.xml --repoToken $env:COVERALLS_REPO_TOKEN --commitId $env:APPVEYOR_REPO_COMMIT --commitBranch $env:APPVEYOR_REPO_BRANCH --commitAuthor $env:APPVEYOR_REPO_COMMIT_AUTHOR --commitEmail $env:APPVEYOR_REPO_COMMIT_AUTHOR_EMAIL --commitMessage $env:APPVEYOR_REPO_COMMIT_MESSAGE --jobId $env:APPVEYOR_JOB_ID --serviceName AppVeyor

    if ($TestExitCode -ne 0) {
        exit $TestExitCode
    }
artifacts:
- path: GoogleTestExtension\GoogleTestAdapterVSIX\bin\Release\GoogleTestAdapterVSIX.vsix
  name: GoogleTestAdapter.vsix
- path: GoogleTestExtension\GoogleTestAdapterVSIX\bin\Release\GoogleTestAdapter.pdb
  name: GoogleTestAdapter.pdb
notifications:
- provider: Email
  to:
  - christian@soltenborn.de
  on_build_success: false
  on_build_failure: true
  on_build_status_changed: true